# run this with: "  CURRENT_UID=$(id -u):$(id -g) docker-compose up ""
version: "3"
services:
  caddy:
    image: caddy:2.3.0-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - bitwarden_net
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SITE_ADDRESS: '$SITE_ADDRESS'
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    cap_add:
      - CAP_NET_BIND_SERVICE
# inspiration
# https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15
# https://medium.com/faun/set-current-host-user-for-docker-container-4e521cef9ffc

  bitwarden:
    image: bitwardenrs/server
    restart: unless-stopped
    expose:
      - '80'
    networks:
      - bitwarden_net
    volumes:
      - bitwarden_data:/data
    environment:
      TZ: 'Australia/Brisbane'
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups
      # Logging connection attemps
      LOG_FILE: '/data/bitwarden.log'
      EXTENDED_LOGGING: 'true'
      LOG_LEVEL: 'warn'

volumes:
  caddy_data:
  caddy_config:
  bitwarden_data:

networks:
  bitwarden_net:
