version: '3.8'

services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - USER=$USER
      - PASSWORD=$PASSWORD
    volumes:
      - ./ddclient.conf:/config/ddclient.conf
    restart: unless-stopped